### ISSUE TITLE
null 

### ISSUE THREAD

**Issue by r00bal** [KitsuneAkvma/goit-react-hw-06-phonebook#1]
https://github.com/KitsuneAkvma/goit-react-hw-06-phonebook/blob/fc164162d7eedeffdc11d7d1662929e205ab280d/src/redux/contactsSlice.js#L4

A co jeżeli pod tym kluczem nic nie będzie w local storage ? do initial state wpadnie null i wywali aplikacje : 
`Uncaught TypeError: Cannot read properties of null (reading 'length')
    at ContactsList (bundle.js:420:29)`

Można dodać małe zabezpieczenie np. 
`const contactsInitialState = JSON.parse(localStorage.getItem('contacts')) || [];`

**Comment by KitsuneAkvma** [comment]
Poprawione i sprawdzone, wszystko już działa poprawnie. Dziękuję za wyłapanie tego. Nie ukrywam że mnie rozbawiła całą banalność tego problemu #1
