### ISSUE TITLE
Redux

### ISSUE THREAD

**Issue by r00bal** [KitsuneAkvma/goit-react-hw-06-phonebook#2]
https://github.com/KitsuneAkvma/goit-react-hw-06-phonebook/blob/fc164162d7eedeffdc11d7d1662929e205ab280d/src/components/App.jsx#L13-L72

Używasz reduxa ale dalej pchasz wszystko propsami do dzieci. Masz teraz globalny stan, możesz wyciągać propsy i tworzyć handlary z dispatchem w komponentach które faktycznie ich używają. Twój app komponent mógłby wyglądać tak:
```
export const App = () =>  ( 
     <> 
       <GlobalStyle /> 
       <Container className="App"> 
         <ContactCreationForm /> 
         <ContactsList /> 
       </Container> 
     </> 
   ); 
```

**Comment by KitsuneAkvma** [comment]
#2 Jak w opisie, poprawiłem to już - faktycznie zapomniałem po co ten redux tak faktycznie jest :/ Skorzystałem też z okazji i przeniosłem event handlery do komponentów, które ich używają.
